### ISSUE TITLE
Click here and make a comment to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/basel-october-developers#1]
Leave a comment here to be added as a collaborator for this repository! 🎉 

Say anything - maybe you can tell us if you've ever used Git or GitHub before, what you'd like to learn, or where you're from. 😄

**Comment by stoe** [comment]
:wave: y'all

**Comment by githubteacher** [comment]
:tada: @stoe is now a repository collaborator. :balloon:

**Comment by epijim** [comment]
:cheese:

**Comment by hibellm** [comment]
Give me access please!

**Comment by reikoch** [comment]
hello, i was here

**Comment by crichID** [comment]
:wave:

**Comment by christof-binder** [comment]
hello from me too

**Comment by feuerbaa** [comment]
I'm here, too :)

**Comment by zawadzkm** [comment]
It doestn't work! Fix it ASAP!

**Comment by githubteacher** [comment]
:tada: @epijim, @hibellm, @reikoch, @crichID, @christof-binder, @feuerbaa, and @zawadzkm are now  repository collaborators. :balloon:

**Comment by popovaj** [comment]
Hi, this is my comment

**Comment by schickimiki** [comment]
Yes, made it in too! :-)

**Comment by githubteacher** [comment]
:tada: @popovaj and @schickimiki are now  repository collaborators. :balloon:

**Comment by gemmeket** [comment]
comment to join

**Comment by githubteacher** [comment]
:tada: @gemmeket is now a repository collaborator. :balloon:
